export type ThemeId = 'coral' | 'neon' | 'violet' | 'emerald' | 'crimson';

export interface Theme {
  id: ThemeId;
  name: string;
  /** Description shown in the Settings picker */
  tagline: string;
  /** CSS gradient stops for the preview swatch (from → to) */
  gradientFrom: string;
  gradientVia?: string;
  gradientTo: string;
  /** Full set of CSS custom properties to inject on <html> */
  vars: Record<string, string>;
}

export const themes: Theme[] = [
  // ─── 1. Sunset Coral (default) ────────────────────────────────────────────
  {
    id: 'coral',
    name: 'Sunset Coral',
    tagline: 'Warm terracotta for late-night sessions',
    gradientFrom: '#ff6b3d',
    gradientVia: '#e07a5f',
    gradientTo: '#ffb59d',
    vars: {
      '--color-surface':                    '#1a110e',
      '--color-surface-dim':                '#1a110e',
      '--color-surface-bright':             '#423631',
      '--color-surface-container-lowest':   '#140d0a',
      '--color-surface-container-low':      '#231713',
      '--color-surface-container':          '#271b18',
      '--color-surface-container-high':     '#322521',
      '--color-surface-container-highest':  '#3d2f2b',
      '--color-surface-variant':            '#53433e',
      '--color-surface-tint':               '#ffb59d',
      '--color-primary':                    '#ffb59d',
      '--color-primary-container':          '#7d2e0e',
      '--color-primary-fixed':              '#ffdbd0',
      '--color-primary-fixed-dim':          '#ffb59d',
      '--color-on-primary':                 '#5c1700',
      '--color-on-primary-container':       '#ffdbd0',
      '--color-secondary':                  '#e8c06a',
      '--color-secondary-container':        '#5a3d00',
      '--color-on-secondary':               '#3e2a00',
      '--color-on-secondary-container':     '#ffdea4',
      '--color-tertiary':                   '#b9c3ff',
      '--color-tertiary-container':         '#3840a0',
      '--color-on-tertiary':                '#202c75',
      '--color-on-tertiary-container':      '#dde1ff',
      '--color-on-surface':                 '#f0ddd9',
      '--color-on-surface-variant':         '#d8c2bb',
      '--color-outline':                    '#a08c86',
      '--color-outline-variant':            '#53433e',
      '--color-inverse-surface':            '#f0ddd9',
      '--color-inverse-on-surface':         '#392017',
      '--color-inverse-primary':            '#903b1f',
      '--color-background':                 '#1a110e',
      '--color-on-background':              '#f0ddd9',
      '--color-error':                      '#ffb4ab',
      '--color-error-container':            '#93000a',
      '--color-on-error':                   '#690005',
      '--color-on-error-container':         '#ffdad6',
    },
  },

  // ─── 2. Neon Nocturne (original teal) ─────────────────────────────────────
  {
    id: 'neon',
    name: 'Neon Nocturne',
    tagline: 'Electric teal for the night shift',
    gradientFrom: '#003b34',
    gradientVia: '#2de2c5',
    gradientTo: '#5affe1',
    vars: {
      '--color-surface':                    '#0f131b',
      '--color-surface-dim':                '#0f131b',
      '--color-surface-bright':             '#353941',
      '--color-surface-container-lowest':   '#0a0e15',
      '--color-surface-container-low':      '#181c23',
      '--color-surface-container':          '#1c2027',
      '--color-surface-container-high':     '#262a32',
      '--color-surface-container-highest':  '#31353d',
      '--color-surface-variant':            '#3b4a46',
      '--color-surface-tint':               '#5affe1',
      '--color-primary':                    '#5affe1',
      '--color-primary-container':          '#003b34',
      '--color-primary-fixed':              '#5affe1',
      '--color-primary-fixed-dim':          '#2de2c5',
      '--color-on-primary':                 '#00201a',
      '--color-on-primary-container':       '#a0ffe9',
      '--color-secondary':                  '#92ccff',
      '--color-secondary-container':        '#00497a',
      '--color-on-secondary':               '#001d31',
      '--color-on-secondary-container':     '#cce5ff',
      '--color-tertiary':                   '#c8b9ff',
      '--color-tertiary-container':         '#4a3f8f',
      '--color-on-tertiary':                '#1e1460',
      '--color-on-tertiary-container':      '#e5dcff',
      '--color-on-surface':                 '#dfe2ed',
      '--color-on-surface-variant':         '#bacac4',
      '--color-outline':                    '#84948f',
      '--color-outline-variant':            '#3b4a46',
      '--color-inverse-surface':            '#dfe2ed',
      '--color-inverse-on-surface':         '#2d3038',
      '--color-inverse-primary':            '#006b5c',
      '--color-background':                 '#0f131b',
      '--color-on-background':              '#dfe2ed',
      '--color-error':                      '#ffb4ab',
      '--color-error-container':            '#93000a',
      '--color-on-error':                   '#690005',
      '--color-on-error-container':         '#ffdad6',
    },
  },

  // ─── 3. Violet Dusk (purple / indigo) ─────────────────────────────────────
  {
    id: 'violet',
    name: 'Violet Dusk',
    tagline: 'Deep purple haze and dreamy indigo',
    gradientFrom: '#4f378b',
    gradientVia: '#9b5de5',
    gradientTo: '#d0bcff',
    vars: {
      '--color-surface':                    '#13101a',
      '--color-surface-dim':                '#13101a',
      '--color-surface-bright':             '#393447',
      '--color-surface-container-lowest':   '#0e0b14',
      '--color-surface-container-low':      '#1c1923',
      '--color-surface-container':          '#211f26',
      '--color-surface-container-high':     '#2b2930',
      '--color-surface-container-highest':  '#36333b',
      '--color-surface-variant':            '#49454e',
      '--color-surface-tint':               '#d0bcff',
      '--color-primary':                    '#d0bcff',
      '--color-primary-container':          '#4f378b',
      '--color-primary-fixed':              '#eaddff',
      '--color-primary-fixed-dim':          '#d0bcff',
      '--color-on-primary':                 '#381e72',
      '--color-on-primary-container':       '#eaddff',
      '--color-secondary':                  '#ccc2dc',
      '--color-secondary-container':        '#4a4458',
      '--color-on-secondary':               '#332d41',
      '--color-on-secondary-container':     '#e8def8',
      '--color-tertiary':                   '#efb8c8',
      '--color-tertiary-container':         '#633b48',
      '--color-on-tertiary':                '#4a2532',
      '--color-on-tertiary-container':      '#ffd8e4',
      '--color-on-surface':                 '#e6e1e5',
      '--color-on-surface-variant':         '#cac4d0',
      '--color-outline':                    '#948f99',
      '--color-outline-variant':            '#49454e',
      '--color-inverse-surface':            '#e6e1e5',
      '--color-inverse-on-surface':         '#313033',
      '--color-inverse-primary':            '#6750a4',
      '--color-background':                 '#13101a',
      '--color-on-background':              '#e6e1e5',
      '--color-error':                      '#ffb4ab',
      '--color-error-container':            '#93000a',
      '--color-on-error':                   '#690005',
      '--color-on-error-container':         '#ffdad6',
    },
  },

  // ─── 4. Emerald Night (deep green) ────────────────────────────────────────
  {
    id: 'emerald',
    name: 'Emerald Night',
    tagline: 'Forest-deep greens for focus mode',
    gradientFrom: '#003920',
    gradientVia: '#059669',
    gradientTo: '#6dd5a1',
    vars: {
      '--color-surface':                    '#0d1a15',
      '--color-surface-dim':                '#0d1a15',
      '--color-surface-bright':             '#333f3a',
      '--color-surface-container-lowest':   '#08110d',
      '--color-surface-container-low':      '#182319',
      '--color-surface-container':          '#1b2b1e',
      '--color-surface-container-high':     '#253528',
      '--color-surface-container-highest':  '#2f3f32',
      '--color-surface-variant':            '#3c4b41',
      '--color-surface-tint':               '#6dd5a1',
      '--color-primary':                    '#6dd5a1',
      '--color-primary-container':          '#005231',
      '--color-primary-fixed':              '#89f2bc',
      '--color-primary-fixed-dim':          '#6dd5a1',
      '--color-on-primary':                 '#003920',
      '--color-on-primary-container':       '#89f2bc',
      '--color-secondary':                  '#b3ccbc',
      '--color-secondary-container':        '#344b3f',
      '--color-on-secondary':               '#1e352a',
      '--color-on-secondary-container':     '#cfe9d8',
      '--color-tertiary':                   '#a0cfcf',
      '--color-tertiary-container':         '#274e4e',
      '--color-on-tertiary':                '#0b3637',
      '--color-on-tertiary-container':      '#bfebeb',
      '--color-on-surface':                 '#dde5de',
      '--color-on-surface-variant':         '#bec8be',
      '--color-outline':                    '#899089',
      '--color-outline-variant':            '#3c4b41',
      '--color-inverse-surface':            '#dde5de',
      '--color-inverse-on-surface':         '#2d332e',
      '--color-inverse-primary':            '#006b41',
      '--color-background':                 '#0d1a15',
      '--color-on-background':              '#dde5de',
      '--color-error':                      '#ffb4ab',
      '--color-error-container':            '#93000a',
      '--color-on-error':                   '#690005',
      '--color-on-error-container':         '#ffdad6',
    },
  },

  // ─── 5. Crimson Steel (red / rose) ────────────────────────────────────────
  {
    id: 'crimson',
    name: 'Crimson Steel',
    tagline: 'Bold red intensity with steely depth',
    gradientFrom: '#920020',
    gradientVia: '#e11d48',
    gradientTo: '#ffb3ae',
    vars: {
      '--color-surface':                    '#1a0d0d',
      '--color-surface-dim':                '#1a0d0d',
      '--color-surface-bright':             '#412525',
      '--color-surface-container-lowest':   '#140808',
      '--color-surface-container-low':      '#231313',
      '--color-surface-container':          '#2b1615',
      '--color-surface-container-high':     '#362020',
      '--color-surface-container-highest':  '#422a2a',
      '--color-surface-variant':            '#534040',
      '--color-surface-tint':               '#ffb3ae',
      '--color-primary':                    '#ffb3ae',
      '--color-primary-container':          '#920020',
      '--color-primary-fixed':              '#ffdad8',
      '--color-primary-fixed-dim':          '#ffb3ae',
      '--color-on-primary':                 '#680012',
      '--color-on-primary-container':       '#ffdad8',
      '--color-secondary':                  '#e7bdb7',
      '--color-secondary-container':        '#5d3f3a',
      '--color-on-secondary':               '#442925',
      '--color-on-secondary-container':     '#ffdad6',
      '--color-tertiary':                   '#e4c28b',
      '--color-tertiary-container':         '#5a3f0c',
      '--color-on-tertiary':                '#3f2900',
      '--color-on-tertiary-container':      '#ffdea2',
      '--color-on-surface':                 '#f0dedd',
      '--color-on-surface-variant':         '#d8c2c0',
      '--color-outline':                    '#a08886',
      '--color-outline-variant':            '#534040',
      '--color-inverse-surface':            '#f0dedd',
      '--color-inverse-on-surface':         '#3d1f1e',
      '--color-inverse-primary':            '#b81c2e',
      '--color-background':                 '#1a0d0d',
      '--color-on-background':              '#f0dedd',
      '--color-error':                      '#ffb4ab',
      '--color-error-container':            '#93000a',
      '--color-on-error':                   '#690005',
      '--color-on-error-container':         '#ffdad6',
    },
  },
];

/** Lookup a theme by ID, falling back to the neon theme. */
export function getTheme(id: ThemeId): Theme {
  return themes.find((t) => t.id === id) ?? themes.find((t) => t.id === 'neon') ?? themes[0];
}
